name: Build Debian Package

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install packaging tools
        run: |
          sudo apt update
          sudo apt install -y \
            devscripts \
            equivs

      - name: Install build dependencies
        run: |
          sudo mk-build-deps \
            --install \
            --remove \
            --tool "apt-get -y --no-install-recommends" \
            debian/control
            
      - name: Fix permissions
        run: |
          chmod +x debian/rules
    
      - name: Build
        run: |
          dpkg-buildpackage -us -uc -b

      - uses: actions/upload-artifact@v4
        with:
          name: cine-deb
          path: ../*.deb
